= Fun.CQRS
// :toc: macro
:toc2:
:linkcss:
:linkattrs:
:icons: font
:source-highlighter: pygments
:pygments-style: manni
:pygments-linenums-mode: inline

## Introduction

**Fun.CQRS** is a Scala library for building CQRS/ES application. It provides the basic blocks to build event driven aggregates with **Event Sourcing**.

**Fun.CQRS** provides a out-of-the-box `AkkaBackend` and a `InMemoryBackend` for testing. However, it's designed as such that other backend implementations are possible. For instance, an alternative Akka backend based on https://github.com/RBMHTechnology/eventuate[Eventuate, window="_blank"], a Slick backend or RxScala backend could be implementated and plugged in easily.

When using the `AkkaBackend`, Aggregates are immutable classes (case class) that live inside an `Actor`. You don't have to deal much with Akka and it's powerful abstractions, instead you concentrate in modeling your aggregate behavior and its protocol (`Commands` and `Events`). However you still need a minimal understanding of how Akka works and how to configure Akka Persistence to use your persistence plugin of choice.

That said, in **Fun.CQRS**, Aggregates are NOT Actors. The **Actor System** is used as a middleware to manage the aggregates, hold them in-memory, store events, recover aggregate states and generate read models via  **Events Projections**

## Usage Example

In the following section we will build a simple aggregate. As an example use case we build a **Lottery** application. This example is also available as a running sample application in the project repository in https://github.com/strongtyped/fun-cqrs[GitHub].

A **Lottery** application has the following requirements:

- An user can create a new lottery game

- An user can add participants +
  **condition**: a participant can only be added once +
  **condition**: a participant can only be added if a winner is not yet selected +

- An user can remove a participant +
	**condition**: if a winner is not yet selected +

- An user can remove all participants +
	**condition**: if a winner is not yet selected +

- A user can run the lottery which will select a winner +
 	**condition**: we can only select a winner if there is at least one participant +
 	**condition**: we can only select a winner once, afterwards an error is produced when trying to select a new winner +

### Type-safe IDs

**Fun.CQRS** uses type-safe IDs for aggregates. The ID itself must be of type String, but it must be wrapped in a aggregate specific ID type to be used by the system. As such, we avoid ID clashing. It also provides better logging as we can clear see in the logs from each aggregate it comes from.

First we define a type representing the Aggregate ID. We define it by extending the trait `io.funcqrs.AggregateId`.

[source,scala]
----
import io.funcqrs.AggregateId
include::../../samples/lottery/src/main/scala/lottery/domain/model/Lottery.scala[tags=lottery-id]
----
(ref: https://github.com/strongtyped/fun-cqrs/blob/master/samples/lottery/src/main/scala/lottery/domain/model/Lottery.scala[Lottery.scala, window="_blank"])

### Lottery Protocol

Next we define a Protocol for a Lottery.

A `Protocol` is the set of `Commands` and `Events` for a given Aggregate. An Aggregate can only receive `Commands` from its `Protocol`. Its command handlers can only emit `Events` that belong to this same `Protocol`. And finally, event listeners that will instantiate or update an `Aggregate` can only react to `Events` define by the `Protocol`.

Therefore, an Aggregate's Protocol defines the totallity of operations and effects of a given Aggregate.

The code below demonstrates how to define a protocol.

[source,scala]
----
import io.funcqrs._
include::../../samples/lottery/src/main/scala/lottery/domain/model/Lottery.scala[tags=lottery-protocol]
----
(ref: https://github.com/strongtyped/fun-cqrs/blob/master/samples/lottery/src/main/scala/lottery/domain/model/Lottery.scala[Lottery.scala, window="_blank"])

<1> A Protocol is defined as a Scala object (not a class) and it extends the trait `ProtocolLike`.
`ProtocolLike` trait brings two new traits in scope: `ProtocolCommand` and `ProtocolEvent`.
<2> Each Lottery Command extends `ProtocolCommand` via sealed trait `LotteryCommnad`.
<3> Each Lottery Event extends `ProtocolEvent` via sealed trait `LotteryEvent`.
`LotteryEvent` is enriched (via `MetadataFacet`) with `LotteryMetadata`.
The `LotteryMetadata` has some basic information about the event, for instance:
<4> The `AggregateId` for each it was generated.
<5> The `CommandId` that originated the `Event`.
<6> A unique `EventId`.
<7> The event date time.
<8> One or more `Tags`  (we'll see later why tagging is important).


### Coding the Aggregate

The next step is to code the  aggregate itself.

[source,scala]
----
import io.funcqrs.AggregateLike
include::../../samples/lottery/src/main/scala/lottery/domain/model/Lottery.scala[tags=lottery-aggregate]
----
(ref: https://github.com/strongtyped/fun-cqrs/blob/master/samples/lottery/src/main/scala/lottery/domain/model/Lottery.scala[Lottery.scala, window="_blank"])

We define the **Lottery** aggregate by extending the trait `io.funcqrs.AggregateLike`. As a consequence we need to define two type members:

<1> The `Id` which should point to an `AggregateId`. In our case the previously defined `LotteryId`.
<2> The `Protocol` which in our case will point to `LotteryProtocol`. Remember: `LotteryProtocol` is an object. To access its type we must write `LotteryProtocol.type`. `LotteryProtocol` gives us the object singleton instance.

[TIP]
====
The `Lottery` aggregate is a simple case class with methods to 'modify' its state by copying the case class and returning it. It does NOT check the invariants of the aggregate `Lottery` and it doesn't work at the level of `Commands` and `Events`. This is rather a design choice. Nothing forbid us to have `Lottery` reacting direct to `Commands` and `Events` and enforcing its invariants.

For this example we will keep it as a mere data container of the aggregate state. The invariants will be enforced by the `Behavior` we will implement in the next section.
====


### Aggregate Behavior

Up to now, we have an Aggregate with a type-safe **Id** and its **Protocol** defining all possible `Commands` and `Evetns`. We still need a way to bind each `Command` to the right operation in the aggregate, let it produces the right `Events` and react to the `Events` accordingly. That all respecting the invariants of the `Lottery` aggregate.

The `Behavior` can be define by means of a declarative **DSL**. It is defined in terms of `Bindings`. A `Binding` describe the different **Command Handlers** and **Event Listerners**.

There two kinds of **Command Handlers**. Handlers that produce `Events` and handlers that reject commands, also know as 'guard clauses'.

We also make a distinction between `Commands` and `Events` that instantiate an Aggregate (creational `Commands` and `Events`) and those that must be validated against an existing Aggregate instance (update `Commands` and `Events`). This is done by defining the `Bindings` inside `whenCreating` and `whenUpdating` blocks.

[TIP]
====
When updating, we need to have access to the current state of the  Aggregate . Therefore, `whenUpdating` blocks requires a function __Aggregate => Binding__ where the function input is the current state of the Aggregate.
====

The code below demonstrate how we can build a `Behavior` with the help of the **Behavior DSL**.

[source,scala]
----
import io.funcqrs.behavior.Behavior
import io.funcqrs.dsl.BehaviorDsl.api._
include::../../samples/lottery/src/main/scala/lottery/domain/model/Lottery.scala[tags=lottery-behavior]
----
(ref: https://github.com/strongtyped/fun-cqrs/blob/master/samples/lottery/src/main/scala/lottery/domain/model/Lottery.scala[Lottery.scala, window="_blank"])

<1> `whenCreating` block defines **Command Handlers** and **Event Listeners** responsible for initialising a `Lottery` aggregate. You can defined as many as you want, but typically there is only one **handler** and one **listener**.
<2> `whenUpdating` block defines **Command Handlers** and **Event Listeners** responsible for updating an existent Aggregate instance. Note that the current lottery state is passed as input parameter to the function.
<3> `reject` handlers are **command handlers** that reject a `Command` if a given condition is fulfilled. Note that `reject` handlers are defined using `PartialFunctions` and typically they include a 'guard' per case.
<4> Different **Command Handlers** and **Event Listeners** may be defined.
<5> In some situations, an `Command` may produce more than one `Event`. In that case, we must call `handler.manyEvent` because function will return a `List[Event]`

### Configuring the Aggregate to live inside Akka

In this last step we configure the **Akka Backend** with our **Lottery** aggregate. the configuration is quite straight forward.

[source,scala]
----
import io.funcqrs.backend.akka.api._
import akka.actor.ActorSystem
import lottery.domain.model.Lottery
import io.funcqrs.backend.akka.AggregateService

include::../../samples/lottery/src/main/scala/lottery/app/Main.scala[tags=lottery-actor]
----
(ref: https://github.com/strongtyped/fun-cqrs/tree/master/samples/lottery/src/main/scala/lottery/app/Main.scala[Main.scala, window="_blank"])

<1> We create an `AkkaBackend` in-place.
<2> The `AkkaBackend` will start its own `ActorSystem`, but of course you can use own `ActorSystem` by overriding `AkkaBackend.actorSystem`
<3> The `AkkaBackend` requires a `EventsSourceProvider` that will be used to query the event store. This is needed for the projections. We'll come back to that on the **Projection** section.
<4> We declare that `Lottery` is an Aggregate and pass the behavior method defined in its companion object. The full syntax is actually `aggregate[Lottery](id => Loggery.behavior(id))`



### Using the Aggregate

Once the `Lottery` aggregate is configured, we request an `AggregateRef` for a `Lottery`. Much like in **Akka** where we can't have access to the Actor itself, in **Fun.CQRS** we don't have direct access to the aggregate. The `Lottery` aggregate will live inside an actor, but instead of working with its `ActorRef` we work with a fully typed `AggregateRef`.

[source,scala]
----
import lottery.domain.model.LotteryId
import lottery.domain.model.LotteryProtocol._

include::../../samples/lottery/src/main/scala/lottery/app/Main.scala[tags=lottery-run]
----
(ref: https://github.com/strongtyped/fun-cqrs/tree/master/samples/lottery/src/main/scala/lottery/app/Main.scala[Main.scala, window="_blank"])

The `lotteryRef` can be used to send commands to the aggregate. Since we are using a Akka backend, all calls return a `Future`. In the event of a successful command, we get back a `Future` with the list of generated events. Otherwise a failed `Future` with an exception.

<1> We request a `AggregateRef` for a `Lottery` using a unique ID.
<2> We send a create command to the `Lottery` aggregate via the `lotteryRef`
<3> We send four AddParticipant commands for four well-known musicians.
<4> Finally we run the **Lottery**
<5> The result is a `Future` holding all `Events` concatenated in a single `Seq` of `Events`.

[TIP]
====
`AggregateRef` is **NOT** an `ActorRef`. However, it does mimic the `ActorRef` API with methods like '?' (ask) and '!' (tell). This is simply because 'tell' and 'ask' are very idiomatic methods for sending `Commands`.

Behind the scenes the `Commands` will be forwarded to the right `Actor` (when using the `AkkaBackend`) holding the Aggregate instance for the passed Id.

When using other backends, the `AggregateRef` may point to other kind of objects, for instance a service or a in-memory data structure.
====

## Projections
TODO - check Lottery sample for the time being

## Akka Configuration
TODO - check Lottery sample for the time being

## Testing
TODO - check Lottery sample for the time being

## Project Information

**Fun.CQRS** is open source software. Source code is available at: +
https://github.com/strongtyped/fun-cqrs (development branch)

Stable and released branch can be found at: +
https://github.com/strongtyped/fun-cqrs/tree/master

### Project artifact
The artifacts are published to Sonatype Repository. Simply add the following to your build.sbt.

```scala
libraryDependencies += "io.strongtyped" %% "fun-cqrs-akka" % "0.3.0-SNAPSHOT"
```

If you want to hack **Fun.CQRS** and develop your own backend, you can import only the core module.
The core module does NOT include the Akka backend.
```scala
libraryDependencies += "io.strongtyped" %% "fun-cqrs-core" % "0.3.0-SNAPSHOT"
```



### License
This software is licensed under the Apache 2 license, quoted below.

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this project except in compliance with
the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific
language governing permissions and limitations under the License.

Copyright 2014 Strong[Typed] (@StrongTyped)

### Contribution policy

Contributions via GitHub pull requests are gladly accepted from their original author. Along with any pull requests, please state that the contribution is your original work and that you license the work to the project under the project's open source license. Whether or not you state this explicitly, by submitting any copyrighted material via pull request, email, or other means you agree to license the material under the project's open source license and warrant that you have the legal authority to do so.
