= Fun.CQRS
//:toc: macro
//:toc:
//:toc-placement: preamble
:toc2:
:linkcss:
:linkattrs:
:icons: font
:source-highlighter: pygments
:pygments-style: manni
:pygments-linenums-mode: inline
:sectlinks:
:sectanchors:

//toc::[]

## Introduction

**Fun.CQRS** is a Scala library for building CQRS/ES application. It provides the basic blocks to build event driven aggregates with **Event Sourcing**.

**Fun.CQRS** provides a out-of-the-box `AkkaBackend` and a `InMemoryBackend` for testing. However, it's designed as such that other backend implementations are possible. For instance, an alternative Akka backend based on https://github.com/RBMHTechnology/eventuate[Eventuate, window="_blank"], a Slick backend or RxScala backend could be implementated and plugged in easily.

When using the `AkkaBackend`, Aggregates are immutable classes (case class) that live inside an `Actor`. You don't have to deal much with Akka and it's powerful abstractions, instead you concentrate in modeling your aggregate behavior and its protocol (`Commands` and `Events`). However you still need a minimal understanding of how Akka works and how to configure Akka Persistence to use your persistence plugin of choice.

That said, in **Fun.CQRS**, Aggregates are NOT Actors. The **Actor System** is used as a middleware to manage the aggregates, hold them in-memory, store events, recover aggregate state and generate read models through  **Event Projections**


## Project Information

**Fun.CQRS** is open source software. Source code is available at: +
https://github.com/strongtyped/fun-cqrs (development branch)

Stable and released branch can be found at: +
https://github.com/strongtyped/fun-cqrs/tree/master

**Project artifact** +
The artifacts are published to Sonatype Repository. Simply add the following to your build.sbt.

```scala
libraryDependencies += "io.strongtyped" %% "fun-cqrs-akka" % "0.4.3"
```

If you want to hack **Fun.CQRS** and develop your own backend, you can import only the core module.
The core module does NOT include the Akka backend.
```scala
libraryDependencies += "io.strongtyped" %% "fun-cqrs-core" % "0.4.3"
```

## Command Model

In the following section we will build a simple  **Lottery** application. +
This example is also available as a running sample application in the project repository in https://github.com/strongtyped/fun-cqrs[GitHub].

A **Lottery** application has the following requirements:

- An user can create a new lottery game

- An user can add participants +
  **condition**: a participant can only be added once +
  **condition**: a participant can only be added if a winner is not yet selected +

- An user can remove a participant +
	**condition**: if a winner is not yet selected +

- An user can remove all participants +
	**condition**: if a winner is not yet selected +

- A user can run the lottery which will select a winner +
 	**condition**: we can only select a winner if there is at least one participant +
 	**condition**: we can only select a winner once, afterwards an error is produced when trying to select a new winner +


### Type-safe IDs

**Fun.CQRS** uses type-safe IDs for aggregates. The ID itself must be of type String, but it must be wrapped in a aggregate specific ID type to be used by the system. As such, we avoid ID clashing and it provides better logging as we can clearly see in the logs from each aggregate it comes from.

First we define a type representing the Aggregate ID. We define it by extending the trait `io.funcqrs.AggregateId`.

[source,scala]
----
import io.funcqrs.AggregateId
include::../../samples/lottery/src/main/scala/lottery/domain/model/Lottery.scala[tags=lottery-id]
----
(ref: https://github.com/strongtyped/fun-cqrs/blob/master/samples/lottery/src/main/scala/lottery/domain/model/Lottery.scala[Lottery.scala, window="_blank"])



### Lottery Protocol

Next we define a Protocol for a Lottery.

A `Protocol` is the set of `Commands` and `Events` for a given Aggregate. An Aggregate can only receive `Commands` from its `Protocol`. Its command handlers can only emit `Events` that belong to this same `Protocol`. And finally, event listeners that will instantiate or update an `Aggregate` can only react to `Events` define by the `Protocol`.

Therefore, an Aggregate's Protocol defines the totallity of operations and effects of a given Aggregate.

The code below demonstrates how to define a protocol.

[source,scala]
----
import io.funcqrs._
include::../../samples/lottery/src/main/scala/lottery/domain/model/Lottery.scala[tags=lottery-protocol]
----
(ref: https://github.com/strongtyped/fun-cqrs/blob/master/samples/lottery/src/main/scala/lottery/domain/model/Lottery.scala[Lottery.scala, window="_blank"])

<1> A Protocol is defined as a Scala object (not a class) and it extends the trait `io.funcqrs.ProtocolLike`. +
`ProtocolLike` trait brings two new traits in scope: `ProtocolCommand` and `ProtocolEvent`.
<2> Each Lottery Command extends `ProtocolCommand` via sealed trait `LotteryCommnad`.
<3> Each Lottery Event extends `ProtocolEvent` via sealed trait `LotteryEvent`. +
`LotteryEvent` is enriched (via `MetadataFacet`) with `LotteryMetadata`.
The `LotteryMetadata` has some basic information about the event, for instance:
<4> The `AggregateId` for each it was generated.
<5> The `CommandId` that originated the `Event`.
<6> A unique `EventId`.
<7> The event date time.
<8> One or more `Tags`  (we'll see later why tagging is important).



### Coding the Aggregate

The next step is to code the  aggregate itself.

[source,scala]
----
import io.funcqrs.AggregateLike
include::../../samples/lottery/src/main/scala/lottery/domain/model/Lottery.scala[tags=lottery-aggregate]
}
----
(ref: https://github.com/strongtyped/fun-cqrs/blob/master/samples/lottery/src/main/scala/lottery/domain/model/Lottery.scala[Lottery.scala, window="_blank"])

We define the **Lottery** aggregate by extending the trait `io.funcqrs.AggregateLike`. As a consequence we need to define two type members:

<1> The `Id` which should point to an `AggregateId`. In our case the previously defined `LotteryId`.
<2> The `Protocol` which in our case will point to `LotteryProtocol`. Remember: `LotteryProtocol` is an object. To access its type we must write `LotteryProtocol.type`. `LotteryProtocol` gives us the object singleton instance.

[TIP]
====
The `Lottery` aggregate is a simple case class with methods to 'modify' its state by copying the case class and returning it. It does NOT check the invariants of the aggregate `Lottery` and it doesn't work at the level of `Commands` and `Events`. This is rather a design choice. Nothing forbid us to have `Lottery` reacting direct to `Commands` and `Events` and enforcing its invariants.

For this example we will keep it as a mere data container of the aggregate state. The invariants will be enforced by the `Behavior` we will implement in the next section.
====



### Aggregate Behavior

Up to now, we have an Aggregate with a type-safe **Id** and its **Protocol** defining all possible `Commands` and `Events`, but we still need to define how each `Command` will be handled, how the `Events` will be generated and how it will react to each `Events`. That all respecting the invariants of the `Lottery` aggregate.

We need to define the Lottery's **Behavior**. +
A `Behavior` itself is just a `PartialFunction` from `State[A] => Actions[A]` where A is the aggregate type (the Lottery in this example), `State` is whether `Unitialized` or `Initialized` and `Actions` is the set of **Command Handlers** and **Event Handlers** (the Actions) that are applicable for a given `State`.

There are two kinds of **Command Handlers**. Handlers that produce `Events` and handlers that reject commands, also know as 'guard clauses'.


The code below demonstrate how we can build a `Behavior` with the help of the **Behavior DSL**.

But before we start we will revisit the `Lottery` aggregate and add some methods returning `Actions` that we can compose and use when defining the final `Behavior`.

We define some **Command Handlers** that reject a command based on the `Command` data or/and aggregate state.
[source,scala]
----
include::../../samples/lottery/src/main/scala/lottery/domain/model/Lottery.scala[tags=lottery-aggregate-guards]
----

Followed by some `Actions` defining **Command Handlers** and **Event Handlers** covering the remaing operations of a `Lottery`.
[source,scala]
----
include::../../samples/lottery/src/main/scala/lottery/domain/model/Lottery.scala[tags=lottery-aggregate-actions]
----

The `Behavior` can now be defined as a `PartialFunction` from different `States`: `Unitialized` and many variations of `Initialized` to `Actions`.


[source,scala]
----
import io.funcqrs.behavior.Behavior
import io.funcqrs.dsl.BehaviorDsl.api._
include::../../samples/lottery/src/main/scala/lottery/domain/model/Lottery.scala[tags=lottery-behavior]
----
(ref: https://github.com/strongtyped/fun-cqrs/blob/master/samples/lottery/src/main/scala/lottery/domain/model/Lottery.scala[Lottery.scala, window="_blank"])

<1> The creation case is a special one. It plays the rol of Aggregate Factory and therfore cannot be defined in the `Lottery` itself.
<2> To make sure we won't run a `Lottery` twice, the next case to match must check if the `Lottery` has already a winner. If that's the case we reject all subsequent commands. The `Lottery` reached its 'end-of-life' can cannot evolve its state anymore.
<3> While the `Lottery` has no partipants, it can only accept subscriptions and reject the `Run` command. Therefore this state is the composition of `canNotRunWithoutParticipants` and `acceptParticipants` Actions.
<4> As soon the `Lottery` has at least one participant it can accept new participatns (`acceptParticipants`), reject double booking (`rejectDoubleBooking`), remove participants (`removingParticipants`) and finally we can select a winner by running it (`runTheLottery`).

### Configuring the Aggregate

In this last step we configure the **Akka Backend** with our **Lottery** aggregate. the configuration is quite straight forward.

[source,scala]
----
import io.funcqrs.backend.akka.api._
import akka.actor.ActorSystem
import lottery.domain.model.Lottery
import io.funcqrs.akka.EventsSourceProvider
import io.funcqrs.akka.backend.{ AggregateActorRef, AkkaBackend }
import io.funcqrs.backend.{ Query, QueryByTag }

include::../../samples/lottery/src/main/scala/lottery/app/Main.scala[tags=akka-backend]
include::../../samples/lottery/src/main/scala/lottery/app/Main.scala[tags=lottery-actor]
----
(ref: https://github.com/strongtyped/fun-cqrs/tree/master/samples/lottery/src/main/scala/lottery/app/Main.scala[Main.scala, window="_blank"])

<1> We create an `AkkaBackend` in-place.
<2> The `ActorSystem` to be used.
<3> The `AkkaBackend` requires a `EventsSourceProvider` that will be used to query the event store. This is needed for the projections. We'll come back to that on the **<<_projections>>** section.
<4> We declare that `Lottery` is an Aggregate and pass the behavior method defined in its companion object.




### Using the Aggregate

Once the `Lottery` aggregate is configured, we request an `AggregateRef` for a `Lottery`. Much like in **Akka** where we can't have access to the Actor itself, in **Fun.CQRS** we don't have direct access to the aggregate. The `Lottery` aggregate will live inside an actor, but instead of working with its `ActorRef` we work with a fully typed `AggregateRef`.

[source,scala]
----
import lottery.domain.model.LotteryId
import lottery.domain.model.LotteryProtocol._

include::../../samples/lottery/src/main/scala/lottery/app/Main.scala[tags=lottery-run]
----
(ref: https://github.com/strongtyped/fun-cqrs/tree/master/samples/lottery/src/main/scala/lottery/app/Main.scala[Main.scala, window="_blank"])

The `lotteryRef` can be used to send commands to the aggregate. Since we are using a Akka backend, all calls return a `Future`. In the event of a successful command, we get back a `Future` with the list of generated events. Otherwise a failed `Future` with an exception.

<1> We request a `AggregateRef` for a `Lottery` using a unique ID.
<2> We send a create command to the `Lottery` aggregate via the `lotteryRef`
<3> We send four `AddParticipant` commands for four well-known musicians.
<4> Finally we run the **Lottery**
<5> The result is a `Future` holding all `Events` concatenated in a single `Seq` of `Events`.

[TIP]
====
`AggregateRef` is **NOT** an `ActorRef`. However, it does mimic the `ActorRef` API with methods like '?' (ask) and '!' (tell). This is simply because 'tell' and 'ask' are very idiomatic methods for sending `Commands`.

Behind the scenes `Commands` will be forwarded to the right `Actor` (when using the `AkkaBackend`) holding the Aggregate instance for the passed Id.

When using other backends, the `AggregateRef` may point to other kind of objects, for instance a service or a in-memory data structure.
====


## Query Model

### Projections

So far we have seen how we define and work with Aggregates (the write model). In this section we show how to define **Projections** to generate the read model.

A **Projection** is nothing more than an **Query** and a **Event Listener** to react to each `Events` produced by the **Query**. That said, **Projections** are not only useful for generating read models (aka Views), but also for **Sagas** where `Events` coming from one Aggregate produces `Commands` on another Aggregate.

Furthermore, a **Projection** must keep track of the last processed event and have the means to persist it to avoid reprocessing all the events all over again on each system restart. As such, a **Projection** has a state and its state is the last processed event.

### Event Tagging
When we defined the Lottery Behavior we marked each `Event` with a `Tag`. This categorization is useful when selecting events from the storage in order to generate view models or to run **Sagas**.


Again, this is specific to the backend implementation. For the **AkkaBackend**, we need to 'teach' the Persistence plugin how to read the tags and save it correctly. **Fun.CQRS** provides a `akka.persistence.journal.WriteEventAdapters` implementaiton that translates `io.funcqrs.Tag` to `akka.persistence.journal.Tagged`.

For LevelDb, the configuration consist of adding the following line to the application.conf file.
[source]
----
akka.persistence.journal.leveldb.event-adapters.domain-tagger = "io.funcqrs.akka.DomainEventTagAdapter"
----

The configuration vary depending on the plugin. Check your plugin documentation for information on how to configure `WriteEventAdapters`.

### AkkaBackend Projections

The **AkkaBackend** implements **Projections** on top of the new **http://doc.akka.io/docs/akka/current/scala/persistence-query.html[Akka Persistence Query, window="_blank"]** module.

We <<_configuring_the_aggregate, have seen>> that the **AkkaBackend** requires the definition of a `EventsSourceProvider`. The `EventsSourceProvider` works, as the name says, as a provider of `akka.stream.scaladsl.Source` of Events.


The method `sourceProvider(query: Query): EventsSourceProvider` in `AkkaBackend` must provide a mapping between a **Fun.CQRS** `Query` to a `EventsSourceProvider` configured for your Akka Persistence plugin of choice. In this example, we use the LevelDb plugin and we query on a single tag.


[source,scala]
----
include::../../samples/lottery/src/main/scala/lottery/domain/service/LevelDbTaggedEventsSource.scala[tags=leveldb-events-source]
----
(ref: https://github.com/strongtyped/fun-cqrs/tree/master/samples/lottery/src/main/scala/lottery/domain/service/LevelDbTaggedEventsSource.scala[LevelDbTaggedEventsSource.scala, window="_blank"])

Internaly, we will create a flow from the `Source` and each `Event` will be delivered to our projection. As such, we will be able to react to each `Event` in the system.

### Lottery View Projection
The `LotteryViewProjection` is responsible for handling events, populate a `LotteryView` model and save it in the `LotteryViewRepo` (in-memory repo for this sample application).

[source,scala]
----
include::../../samples/lottery/src/main/scala/lottery/domain/model/LotteryView.scala[tags=lottery-view]
----
(ref: https://github.com/strongtyped/fun-cqrs/tree/master/samples/lottery/src/main/scala/lottery/domain/model/LotteryView.scala[LotteryView.scala, window="_blank"])
[source, scala]
----
include::../../samples/lottery/src/main/scala/lottery/domain/service/LotteryViewProjection.scala[tags=lottery-view-projection]
----
(ref: https://github.com/strongtyped/fun-cqrs/tree/master/samples/lottery/src/main/scala/lottery/domain/service/LotteryViewProjection.scala[LotteryViewProjection.scala, window="_blank"])

### Configuring the View Projection

Similar to the configuration of the aggregate, we must configure the projection in our backend.

[source,scala]
----
import io.funcqrs.backend.akka.api._
import akka.actor.ActorSystem
import lottery.domain.model.Lottery
import io.funcqrs.akka.EventsSourceProvider
import io.funcqrs.akka.backend.{ AggregateActorRef, AkkaBackend }
import io.funcqrs.backend.{ Query, QueryByTag }

  val backend = new AkkaBackend {
    // ommitted - see configuring the aggregate example
  }

include::../../samples/lottery/src/main/scala/lottery/app/Main.scala[tags=lottery-projection]
----
(ref: https://github.com/strongtyped/fun-cqrs/tree/master/samples/lottery/src/main/scala/lottery/app/Main.scala[Main.scala, window="_blank"])


<1> Define the query criteria for `Events` selection. We want all `Events` tagged with the Lottery tag. In other worlds, we want all `Events` from Lottery aggregates.
<2> The `LotteryViewProjection` that will receive each Lottery Event and generate / update the `LotteryView`.
<3> Unique identifier for this projection.
<4> The offset persistence strategy. Projections need to save the last processed event position to avoid replaying all events from the beginning on each system restart. The `BackendOffsetPersistence` means that the bakend (in this case the AkkaBackend) is responsible for managing it. The `AkkaBackend` will save it as a separate message (not a Domain Event) in Akka Persistence. Other options are: `withoutOffsetPersistence` (no persistence at all) or `withCustomOffsetPersistence(strategy: CustomOffsetPersistenceStrategy)` for user defined offset persistence strategy.

## License
This software is licensed under the Apache 2 license, quoted below.

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this project except in compliance with
the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific
language governing permissions and limitations under the License.

Copyright 2014 Strong[Typed] (@StrongTyped)

## Contribution policy

Contributions via GitHub pull requests are gladly accepted from their original author. Along with any pull requests, please state that the contribution is your original work and that you license the work to the project under the project's open source license. Whether or not you state this explicitly, by submitting any copyrighted material via pull request, email, or other means you agree to license the material under the project's open source license and warrant that you have the legal authority to do so.

//toc::[]
