package io.strongtyped.funcqrs.akka

trait AutoGeneratedAggregateId {
  this: AggregateManager =>

  def generateId(): AggregateType#Id

  override def processCreation: Receive = {
    case cmd: AggregateType#Protocol#ProtocolCommand => processAggregateCommand(generateId(), cmd)
  }
}
