package shop.api

import java.util.UUID

import akka.actor.ActorRef
import fun.cqrs.DomainCommand
import play.api.libs.json.{JsResult, JsValue}
import shop.domain.model.{CustomerProtocol, CustomerId, Customer}
import com.softwaremill.macwire._


class CustomerCmdController(val aggregateManager: ActorRef @@ Customer.type)
  extends CommandController with AutoGeneratedId {

  type AggregateType = Customer

  def toCommand(jsValue: JsValue): JsResult[DomainCommand] =
    CustomerProtocol.commandsFormat.reads(jsValue)

  def toAggregateId(id: String): CustomerId = CustomerId.fromString(id)

  def location(id: String): String = s"/customer/$id"
}
