package fun.cqrs.akka

trait AutoGeneratedAggregateId {
  this: AggregateManager =>

  def generateId(): AggregateType#Identifier

  override def processCreation: Receive = {
    case cmd: AggregateType#Protocol#ProtocolCommand => processAggregateCommand(generateId(), cmd)
  }
}
