package fun.cqrs.akka

trait AutoGeneratedAggregateId {
  this: AggregateManager =>

  def generateId: AggregateType#Identifier

  override def processCreation: Receive = {
    case cmd: AggregateType#Protocol#CreateCmd => processAggregateCommand(generateId, cmd)
  }
}
